### ISSUE TITLE
com.android.mms and FileProvider

### ISSUE THREAD

**Issue by tbarthel-fr** [tvbarthel/IntentShare#30]
The target app com.android.mms crashes when an image is send as stream in the shared extras due to orientation check.

As the Uri has a content provider scheme, the com.android.mms skips the Exif check (which seems to be slow) and tries to query the MediaStore.Images.ImageColumns.ORIENTATION : 
http://androidxref.com/5.1.1_r6/xref/packages/apps/Mms/src/com/android/mms/ui/UriImage.java#546

Unfortunately, the default implementation of FileProvider from support-v4 won't return any data for such a query since only OpenableColumns.DISPLAY_NAME and OpenableColumns.SIZE are taken into account : 
http://androidxref.com/5.1.1_r6/xref/frameworks/support/v4/java/android/support/v4/content/FileProvider.java#421

As a result, http://androidxref.com/5.1.1_r6/xref/packages/apps/Mms/src/com/android/mms/ui/UriImage.java#546 will throw an exception.

FileProvider myst be extend in order to handle MediaStore.Images.ImageColumns.ORIENTATION query on our side.

**Comment by vbarthel-fr** [comment]
You were right, when sharing with Messaging (com.android.mms) the FileProvider is queried with a projection `[orientation]`.

**Note:** If you want to test, be aware of the content resolver cache =) If you re-install a version of the sample with the bug, after querying the orientation of the file with this fix, the content resolver will use the cached orientation and won't crash. (at least, it is what I experimented with my phone). SImply use an emulator and wipe the data.
