### ISSUE TITLE
manifest merger failed attribute application@allowbackup value=(false)

### ISSUE THREAD

**Issue by aknkaplanoglu** [tvbarthel/IntentShare#37]
You should not set attribute application@allowbackup value=(false).

**Comment by vbarthel-fr** [comment]
Thanks for having raised this problem =)

An MR has been opened: https://github.com/tvbarthel/IntentShare/pull/38

**Comment by petitTrung** [comment]
Could you put this correction to a new jcenter version please? The actual 0.0.2 can not be compiled in any project.

**Comment by vbarthel-fr** [comment]
Hi @petitTrung 

We will update the library on jcenter asap! Until then you might try to use the "replace" attribut:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
    package="com.your.package"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application
        android:allowBackup="false"
        tools:replace="allowBackup">

        ...

    </application>


</manifest>
```

You should be able to compile your project with this workaround until we push a new version! 

Please, keep us posted =)

**Comment by tbarthel-fr** [comment]
fixed in the last version:
```groovy
compile 'fr.tvbarthel.intentshare:library:0.0.3'
```

```groovy
compile 'fr.tvbarthel.intentshare:picasso-loader:0.0.3'
compile 'fr.tvbarthel.intentshare:glide-loader:0.0.3'
```

**Comment by eddskt** [comment]
Thanks @vbarthel-fr  4 years later, and many searchs, it is the only solution that worked for me
